name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ] # 如果你的主分支叫 main，請改為 main

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x # 根據你的 .NET 版本調整

      - name: Publish
        run: dotnet publish FundCalculator.csproj -c Release -o release --nologo

      - name: Add .nojekyll
        run: touch release/wwwroot/.nojekyll

      - name: Commit to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot